### ISSUE TITLE
Fix types for suspense queries

### ISSUE THREAD

**Issue by benjavicente** [get-convex/convex-react-query#7]
### Problem

`convexQuery` uses types that are only compatible with `useQuery`, even thought `useSuspenseQuery` seems to work ok.
The [example provided by the *tankstack* router docs](https://tanstack.com/router/v1/docs/framework/react/examples/start-convex-trellaux) shows a type error but works fine. The error is:

```txt
Type 'typeof skipToken' is not assignable to type 'QueryFunction<...>'
```

### Notes

The options given to suspense (suspense query and suspense infinite query) are slightly different since them can't be disabled and don't have placeholder data. This specific error comes from the [skipToken, used to type-safety disable queries in assigning it to the `queryFn`](https://tanstack.com/query/v5/docs/framework/react/guides/disabling-queries#typesafe-disabling-of-queries-using-skiptoken). The types of those interfaces in the tankstack query source code can be found [here](https://github.com/TanStack/query/blob/9d99fcb950e04beb14f306942d3c0e198837e21b/packages/react-query/src/types.ts#L34-L57).

### Proposed solution

Since:
- this wrapper only picks `"queryKey" | "queryFn" | "staleTime"` ([see code](https://github.com/get-convex/convex-react-query/blob/76b66933b54faeab5294cc971073259894d9c04c/src/index.ts#L428))
- "queryFn"  is internal and can't be set to the skipToken
- "queryKey" and "staleTime" are both present in suspense and non suspense

The `UseQueryOptions` could be replaced with `UseSuspenseQueryOptions` type with no problems.

If that seems ok, I could open a PR with that fix. 

PD: should tests for the types be added?

**Comment by thomasballinger** [comment]
This is fixed in https://github.com/get-convex/convex-react-query/commit/51015d4d460055a801336aaf681ff330600e37e8, following basically this approach. If "skip" is passed then `UseQueryOptions` are returned, if it isn't then `UseSuspenseQueryOptions` are returned.

It's a messy solution, interested in making it better.
